language: python
python:
    - "2.7"
install: pip install -r requirements.txt
script: python tests.py
jobs:
    include:
        - stage: development
          script: bash dev-script.sh
        - stage: staging
          script: ./staging-script.sh
        - stage: production
