language: python
python:
    - "2.7"
sudo: required
services:
    - docker
before_install:
    - docker build -t hello-docker .
install: pip install -r requirements.txt
script: docker run hello-docker
# jobs:
#     include:
#         - stage: development
#           script:
#               -  ./dev-script-1.sh
#               -  ./dev-script-2.sh
#         - stage: staging
#           script: bash staging-script.sh
#         - stage: production
#           script: ./prod-script.sh
